// -----------------------------------------------------------------------
// <copyright file="SkillIntegrityRule.cs" company="Signal Coding Limited">
//     Copyright 2026 Signal Coding Limited. All rights reserved.
//     Licensed under the Apache License, Version 2.0.
// </copyright>
// -----------------------------------------------------------------------

using SignalSentinel.Core;
using SignalSentinel.Core.Models;
using SignalSentinel.Scanner.SkillParser;

namespace SignalSentinel.Scanner.Rules.SkillRules;

/// <summary>
/// SS-024: Flags Agent Skills that lack integrity artefacts (signatures, checksum files).
/// Maps to OWASP ASI04 (Supply Chain Vulnerabilities).
/// </summary>
/// <remarks>
/// This rule emits a Medium severity finding for every skill that does not ship
/// a sibling signature file. It also computes a content hash (SKILL.md + bundled scripts)
/// which reports expose for customers building their own allowlists.
/// </remarks>
public sealed class SkillIntegrityRule : IRule
{
    /// <inheritdoc />
    public string Id => RuleConstants.Rules.SkillIntegrityVerification;

    /// <inheritdoc />
    public string Name => "Skill Integrity Verification";

    /// <inheritdoc />
    public string OwaspCode => OwaspAsiCodes.ASI04;

    /// <inheritdoc />
    public string Description =>
        "Flags Agent Skills that lack integrity artefacts (signature or checksum files) and exposes content hashes to support allowlisting.";

    /// <inheritdoc />
    public bool EnabledByDefault => true;

    /// <inheritdoc />
    public Task<IEnumerable<Finding>> EvaluateAsync(ScanContext context, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(context);
        cancellationToken.ThrowIfCancellationRequested();

        var findings = new List<Finding>();

        foreach (var skill in context.Skills)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var report = IntegrityVerifier.Verify(skill);

            if (!report.SignaturePresent)
            {
                findings.Add(new Finding
                {
                    RuleId = Id,
                    OwaspCode = OwaspCode,
                    Severity = Severity.Medium,
                    Title = $"Skill Not Signed: {skill.Name}",
                    Description =
                        $"Skill '{skill.Name}' does not ship with an integrity artefact (.sentinel-sig, SHA256SUMS, cosign.sig, or similar). " +
                        "Without a signature or checksum, tampering cannot be detected.",
                    Remediation =
                        "Publish skills with a signature file generated by cosign/sigstore, or at minimum a SHA256SUMS file. " +
                        $"Current content hash (for your records): {report.ContentHash}",
                    ServerName = skill.Name,
                    Evidence = report.ContentHash,
                    Confidence = 0.95,
                    Source = FindingSource.Skill,
                    SkillFilePath = skill.FilePath
                });
            }
        }

        return Task.FromResult<IEnumerable<Finding>>(findings);
    }
}
